# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lol = QtWidgets.QPushButton(self.centralwidget)
        self.lol.setGeometry(QtCore.QRect(0, 210, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lol.setFont(font)
        self.lol.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.lol.setObjectName("lol")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_result.setObjectName("label_result")
        self.result = QtWidgets.QPushButton(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(190, 210, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.result.setObjectName("result")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(0, 120, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.four.setFont(font)
        self.four.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.four.setObjectName("four")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(100, 50, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.two.setFont(font)
        self.two.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(200, 50, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.three.setFont(font)
        self.three.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.three.setObjectName("three")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(0, 50, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.one.setFont(font)
        self.one.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.one.setObjectName("one")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(100, 120, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.five.setFont(font)
        self.five.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(200, 120, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.six.setFont(font)
        self.six.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        self.six.setObjectName("six")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 291, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.lol.setText(_translate("MainWindow", "0"))
        self.label_result.setText(_translate("MainWindow", "TextLabel"))
        self.result.setText(_translate("MainWindow", "="))
        self.four.setText(_translate("MainWindow", "4"))
        self.two.setText(_translate("MainWindow", "2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.one.setText(_translate("MainWindow", "1"))
        self.five.setText(_translate("MainWindow", "5"))
        self.six.setText(_translate("MainWindow", "6"))

    def add_functions(self):
        self.lol.clicked.connect(lambda: self.write_number(self.lol.text()))
        self.one.clicked.connect(lambda: self.write_number(self.one.text()))

    def write_number(self, number):
        if self.label_result.text() == '0':
            self.label_result.setText(number)
        else:
            self.label_result.setText(self.label_result.text() + number)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
